services:
  wordpress:
    build:
      context: .
      dockerfile: ./docker/wordpress/Dockerfile
      args:
        - GID=${GID:-1000}
        - UID=${LOCAL_UID:-1000}
        - SEED_FILE=basic-wordpress-seed.sh
    restart: always
    ports:
      - "8000:80"
    environment:
      SITE_TITLE: Basic
      SITE_URL: ${BASIC_HOST:-http://localhost:8000}
      ADMIN_USERNAME: admin
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: admin
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    healthcheck:
      test: [ "CMD-SHELL", "[ -f /tmp/done ]" ]
      interval: 1s
      timeout: 5s
      retries: 1200
    volumes:
      - ./plugins:/var/www/html/wp-content/plugins
      - ./config/php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    healthcheck:
      # needs to work for both MySQL and mariaDB
      test:
        [
          "CMD-SHELL",
          "mysqladmin -u $$MYSQL_USER -p$$MYSQL_PASSWORD  ping -P 3306 -h localhost | grep -q 'mysqld is alive'"
        ]
      interval: 1s
      timeout: 10s
      retries: 1200
